[tool.poetry]
name = "prosimos"
version = "2.1.0"
description = ""
authors = [
    "Iryna Halenok <iryna.halenok@ut.ee>",
    "Orlenys López Pintado <orlenyslp@gmail.com>",
]
readme = "README.md"
packages = [
    { include = "cli" },
    { include = "prosimos" },
    { include = "bpdfr_discovery" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
click = "^8.4.2"
numpy = "^2.4.6"
pandas = "^2.3.3"
python-dateutil = "^2.9.0"
pytz = "^2026.3"
scipy = "^1.17.1"
pix-framework = "^0.15.0"
pylint = "^4.0.6"
log-distance-measures = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "^9.0.1"

[tool.poetry.scripts]
prosimos = "cli.diff_res_bpsim:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
